### ISSUE TITLE
Shipping option

### ISSUE THREAD

**Issue by Str3tch0** [TreborNamor/Agressive-Bestbuy-Bot#6]
Is there a way to edit the code to select the Free Shipping radio button? currently it defaults to the local pick up shipping option. 
In the bestbuy page source i see this called out for the free shipping radio button <input type="radio" name="availability-selection" id="fulfillment-shipping-gffenwq1qqjv-4pu8be3hkgtxg">

**Comment by Str3tch0** [comment]
#fulfillment-shipping-gffenwq1qqjv-4pu8be3hkgtxg is what i get when i copy the ccs selector info for the radio button but it seems to be hashed and changes for different users

**Comment by Str3tch0** [comment]
and i see this in your code to select the shipping option "#fulfillment_1losStandard0"

**Comment by TreborNamor** [comment]
yes, the shipping option is a little tricky because there is multiple css selectors for almost every product. I found the "#fulfillment_1losStandard0" to be the most used on bestbuy website but it doesn't always work. I just gave the computer the ability to try to click it but skip it if it was not able to locate the radio button.
